### ISSUE TITLE
Roadmap: Add Web Server Package (php, mysql, phpmyadmin, etc)

### ISSUE THREAD

**Issue by Aetherinox** [Aetherinox/proteus-app-manager#10]
## Summary
Add the following apps:
- [x] PHP 7.x - 8.x
  - [x] php 7.3
  - [x] php 7.3-fpm
  - [x] php 7.4
  - [x] php 7.4-fpm
  - [x] php 8.1
  - [x] php 8.1-fpm
  - [x] php 8.2
  - [x] php 8.2-fpm
- [x] PhpMyAdmin + OAuth Libraries
  - [x] 2FA / U2F Plugin requires Composer
  - [x] PhpMyAdmin Themes (mainly dark)
- [x] MySQL
- [ ] MariaDB
- [x] Nginx
- [ ] Apache

**Comment by Aetherinox** [comment]
## Update
**mysql database** package included
- Allows for mysql itself to be installed
- Supports either a `Proteus` setup method, or `mysql_secure_installation`
- Allows for a random 20 character password to be generated after mysql is installed to apply to the root user
  - TODO: Add option to disable root account
- Creates a random 20 character password for a mysql user account
- Includes a very dramatic "password reset" feature for users who have forgot their account password
  - Feature activates on users who already have a password applied to their mysql account
  - User must type an incorrect password three times
  - May add selection based option to allow this feature to be activated at user's request
- Once mysql setup is complete, user gets presented with new password in terminal
  - No echoing to logs
  - Password file created in `/home/$USER/bin/pwd/mysql.pwd` with chmod `600` and chown / chgrp `$USER`
  - User will be nagged to delete this file if it exists every time they open Proteus
  - Primary purpose is to ensure user has written down new mysql password and I don't get hounded on being locked out of their database.
  - No support for providing password in CLI. This is just dumb in regards to user history and the sake of security. User will have to provide password at run-time.
